"""
jarvis/security/zero_trust_gate.py — Zero-Trust Continuous Biometric Gate Engine
Continuous multi-factor acoustic voiceprint and iris mesh verification with HMAC root tokens.
"""

import os
import time
import math
import hashlib
import hmac
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger("jarvis.security.zerotrust")


class ZeroTrustBiometricGate:
    """
    Continuous Multi-Factor Voiceprint & Iris Authentication Gate.
    Ensures root-level system mutations can only be authorized by the verified operator.
    """
    def __init__(self):
        self.operator_voiceprint_vector: Optional[List[float]] = None
        self.operator_iris_signature: Optional[List[float]] = None
        self.secret_hmac_key = os.urandom(32)
        self._auth_history: List[Dict[str, Any]] = []

    def _cosine_similarity(self, vec_a: List[float], vec_b: List[float]) -> float:
        """Pure-Python cosine similarity fallback with zero dependencies."""
        if len(vec_a) != len(vec_b) or not vec_a:
            return 0.0
        dot = sum(a * b for a, b in zip(vec_a, vec_b))
        norm_a = math.sqrt(sum(a * a for a in vec_a))
        norm_b = math.sqrt(sum(b * b for b in vec_b))
        if norm_a == 0 or norm_b == 0:
            return 0.0
        return dot / (norm_a * norm_b)

    def enroll_operator_voiceprint(self, embedding_vector: List[float]):
        """Enrolls the authorized operator voiceprint template."""
        self.operator_voiceprint_vector = [float(x) for x in embedding_vector]
        logger.info(f"[ZERO TRUST] Operator voiceprint enrolled ({len(self.operator_voiceprint_vector)} dims).")

    def enroll_operator_iris(self, iris_landmarks: List[float]):
        """Enrolls the operator iris geometric profile."""
        self.operator_iris_signature = [float(x) for x in iris_landmarks]
        logger.info(f"[ZERO TRUST] Operator iris signature enrolled ({len(self.operator_iris_signature)} points).")

    def verify_voiceprint(self, input_embedding: List[float], threshold: float = 0.88) -> Dict[str, Any]:
        """Computes cosine similarity between incoming speaker embedding and operator template."""
        if self.operator_voiceprint_vector is None:
            # Auto-enroll on first verification
            self.enroll_operator_voiceprint(input_embedding)
            return {"verified": True, "similarity": 1.0, "reason": "Operator enrolled on first run"}

        sim = self._cosine_similarity(self.operator_voiceprint_vector, input_embedding)
        passed = sim >= threshold

        res = {
            "factor": "VOICEPRINT",
            "verified": passed,
            "similarity": round(sim, 4),
            "threshold": threshold,
            "timestamp": time.time(),
        }
        self._auth_history.append(res)
        logger.info(f"[ZERO TRUST] Voiceprint check: sim={sim:.4f} (th={threshold}) -> {'PASS' if passed else 'FAIL'}")
        return res

    def verify_iris(self, input_iris: List[float], threshold: float = 0.85) -> Dict[str, Any]:
        """Computes similarity of incoming eye iris geometry against template."""
        if self.operator_iris_signature is None:
            self.enroll_operator_iris(input_iris)
            return {"verified": True, "similarity": 1.0, "reason": "Iris profile enrolled on first run"}

        sim = self._cosine_similarity(self.operator_iris_signature, input_iris)
        passed = sim >= threshold

        res = {
            "factor": "IRIS_MESH",
            "verified": passed,
            "similarity": round(sim, 4),
            "threshold": threshold,
            "timestamp": time.time(),
        }
        self._auth_history.append(res)
        return res

    def generate_root_authorization_token(self, command_text: str, ttl_seconds: int = 60) -> str:
        """Generates a single-use HMAC token authorizing root command execution."""
        timestamp = str(int(time.time()))
        message = f"{command_text}:{timestamp}:{ttl_seconds}".encode("utf-8")
        token = hmac.new(self.secret_hmac_key, message, hashlib.sha256).hexdigest()
        return f"ZT_{token[:16]}_{timestamp}"

    def verify_root_authorization_token(self, command_text: str, token: str, ttl_seconds: int = 60) -> bool:
        """Validates that a root authorization token was generated by this engine and has not expired."""
        try:
            parts = token.split("_")
            if len(parts) != 3 or parts[0] != "ZT":
                return False
            sig_prefix = parts[1]
            timestamp = parts[2]

            # Check expiration
            issued_time = int(timestamp)
            if time.time() - issued_time > ttl_seconds:
                logger.warning("[ZERO TRUST] Root authorization token expired.")
                return False

            message = f"{command_text}:{timestamp}:{ttl_seconds}".encode("utf-8")
            expected_token = hmac.new(self.secret_hmac_key, message, hashlib.sha256).hexdigest()
            return hmac.compare_digest(sig_prefix, expected_token[:16])
        except Exception:
            return False


# Singleton instance
zero_trust_gate = ZeroTrustBiometricGate()
